language: node_js
services:
  -docker

before_install:
  - docker build -t gunavathiduraisamy/reactapp -f Dockerfile.dev .

scripts:
  - docker run gunavathiduraisamy/react npm run test -- --coverage
